dist: trusty
sudo: false

env:
  global:
    - SONAR_BUILD_TOOL_URL="https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip"
    - SONAR_BUILD_TOOL_ZIP="sonar-build-wrapper.zip"
    - SONAR_ANALYSER_TOOL_URL="https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip"
    - SONAR_ANALYSER_TOOL_ZIP="sonar-scanner.zip"
    - SONAR_TOOLS_DIR="sonar-analysis"
    - SONAR_BUILD_OUTPUT_DIR="bw-output"
    

cache:
  timeout: 600
  directories:
    - $HOME/cache

jobs:
  include:
  - stage: build and analyse
    script: scripts/build_and_analyse.sh    

# Don't copy the following part if your usnig this project as a starting point of yours
# notifications:
#   email: false
#   webhooks:
#     - secure: "ouG1h56cuJejRCsCHZOc4X0lDrpZyaiXOmzYMX0qnKXsjx17ZRMdkunA11pzrABAzO2l4rq5aMMNLs2Obwp/jiuV11SeyucgGzgqwdUQivR9noqpI9yq9VeaRBuK8dHMG0RtRVH0HAdv53VaPBYExj860FdBOUMzgvxE1v7EPIqpfbC9XcIPkZoIkMCP0E8nBE5R3is1ZY49fgFi3+UpQP5EjfeX2E8n0tHzs6uwO7QcnB0GNfUcjKGShjxecPEB77oIv8kcaIEqUBdRsuwwIfidtOsgggGpchaeJ1kEVTESLDz7QPf73ng4j9LP7whb0rtVZYpUr+TI0MoLZu5/WptErelei1eBniHR8CbSbhi6FQ07Pyx7DAc9xmBjgBVbLY/RROGfguAPd+AWn/E6WthN31q6/EpeX7wOkNDjOk6CUPqGgHpQ4BJDy82uV8N3H/uMaonwCeyxKhWxlOWGWBEUwN3rXRt63wMNYABemBiXdjlVxnh1949Drhd+LBS1ebeikq5SmOrZCA2IrHPcTEAtU7bCaCoe5vOm9XYQmxfrNg88aiQR26SjVK2A55x2t8DXqkjS8/7Q9k7gg5CBG5iEOdrSPw8UKTuy2t8SaUlaidyZTdbUT5L3v/UKgucex+hRN8AzWDJ6u9Hl2qdaxZKOSJjo+NV7ZsLxrVvafrg="
#   on_start: always
